// Restaurant data from Franchino er Criminale reviews
const restaurants = [
    {
        id: 1,
        name: "Roscioli",
        category: "pasta",
        categoryLabel: "Pasta",
        rating: 4.8,
        lat: 41.8935,
        lng: 12.4746,
        address: "Via dei Giubbonari, 21, Roma",
        quote: "La carbonara qui è criminale... nel senso buono!",
        specialties: ["Carbonara", "Cacio e Pepe", "Gricia"]
    },
    {
        id: 2,
        name: "Pizzarium",
        category: "pizza",
        categoryLabel: "Pizza",
        rating: 4.9,
        lat: 41.9073,
        lng: 12.4534,
        address: "Via della Meloria, 43, Roma",
        quote: "Bonci è un genio, questa pizza al taglio è da arresto!",
        specialties: ["Pizza al Taglio", "Supplì"]
    },
    {
        id: 3,
        name: "Trapizzino",
        category: "street-food",
        categoryLabel: "Street Food",
        rating: 4.7,
        lat: 41.8753,
        lng: 12.4765,
        address: "Via Giovanni Branca, 88, Roma",
        quote: "Er trapizzino è un'invenzione romana che dovrebbe essere patrimonio UNESCO!",
        specialties: ["Trapizzino alla Coda", "Trapizzino alla Picchiapò"]
    },
    {
        id: 4,
        name: "Da Enzo al 29",
        category: "trattoria",
        categoryLabel: "Trattoria",
        rating: 4.9,
        lat: 41.8894,
        lng: 12.4747,
        address: "Via dei Vascellari, 29, Roma",
        quote: "La cacio e pepe de Enzo te fa piagne dall'emozione!",
        specialties: ["Cacio e Pepe", "Carciofi alla Giudia", "Tiramisù"]
    },
    {
        id: 5,
        name: "Tonnarello",
        category: "pasta",
        categoryLabel: "Pasta",
        rating: 4.6,
        lat: 41.8895,
        lng: 12.4694,
        address: "Via della Paglia, 1, Roma",
        quote: "Porzioni criminali e pasta ancora più criminale!",
        specialties: ["Tonnarelli Cacio e Pepe", "Amatriciana"]
    },
    {
        id: 6,
        name: "Pizzeria Da Baffetto",
        category: "pizza",
        categoryLabel: "Pizza",
        rating: 4.5,
        lat: 41.8982,
        lng: 12.4701,
        address: "Via del Governo Vecchio, 114, Roma",
        quote: "Pizza romana DOC, croccante come deve esse!",
        specialties: ["Pizza Margherita", "Pizza Napoli"]
    },
    {
        id: 7,
        name: "Supplì Roma",
        category: "street-food",
        categoryLabel: "Street Food",
        rating: 4.7,
        lat: 41.8891,
        lng: 12.4731,
        address: "Via di San Francesco a Ripa, 137, Roma",
        quote: "Er supplì co' la mozzarella che fila... criminale!",
        specialties: ["Supplì al Telefono", "Supplì alla Carbonara"]
    },
    {
        id: 8,
        name: "Felice a Testaccio",
        category: "trattoria",
        categoryLabel: "Trattoria",
        rating: 4.8,
        lat: 41.8768,
        lng: 12.4756,
        address: "Via Mastro Giorgio, 29, Roma",
        quote: "La mantecatura della cacio e pepe è uno spettacolo!",
        specialties: ["Cacio e Pepe", "Abbacchio", "Tiramisù"]
    },
    {
        id: 9,
        name: "Pinsere Roma",
        category: "pizza",
        categoryLabel: "Pizza",
        rating: 4.6,
        lat: 41.8987,
        lng: 12.4833,
        address: "Via Flavia, 98, Roma",
        quote: "La pinsa romana fatta come si deve, leggera e croccante!",
        specialties: ["Pinsa Margherita", "Pinsa con Mortadella"]
    },
    {
        id: 10,
        name: "Osteria Bonelli",
        category: "trattoria",
        categoryLabel: "Trattoria",
        rating: 4.5,
        lat: 41.8889,
        lng: 12.5463,
        address: "Viale dell'Acquedotto Alessandrino, 172, Roma",
        quote: "Cucina romana vera, quella de 'na vorta!",
        specialties: ["Rigatoni alla Pajata", "Trippa alla Romana"]
    },
    {
        id: 11,
        name: "Antico Forno Roscioli",
        category: "street-food",
        categoryLabel: "Street Food",
        rating: 4.8,
        lat: 41.8942,
        lng: 12.4755,
        address: "Via dei Chiavari, 34, Roma",
        quote: "La pizza bianca appena sfornata è da denuncia!",
        specialties: ["Pizza Bianca", "Pizza Rossa", "Maritozzi"]
    },
    {
        id: 12,
        name: "Grazia & Graziella",
        category: "pasta",
        categoryLabel: "Pasta",
        rating: 4.4,
        lat: 41.8863,
        lng: 12.4718,
        address: "Largo M.D. Fumasoni Biondi, 5, Roma",
        quote: "Atmosfera trasteverina e piatti che non deludono!",
        specialties: ["Spaghetti alle Vongole", "Carbonara"]
    },
    {
        id: 13,
        name: "Hostaria da Cesare",
        category: "pesce",
        categoryLabel: "Pesce",
        rating: 4.6,
        lat: 41.9423,
        lng: 12.4541,
        address: "Via Crescenzio, 13, Roma",
        quote: "Pesce fresco e preparazione da manuale!",
        specialties: ["Spaghetti alle Vongole", "Fritto Misto"]
    },
    {
        id: 14,
        name: "Dar Poeta",
        category: "pizza",
        categoryLabel: "Pizza",
        rating: 4.5,
        lat: 41.8884,
        lng: 12.4676,
        address: "Vicolo del Bologna, 45, Roma",
        quote: "Il calzone alla nutella è er crimine perfetto!",
        specialties: ["Pizza", "Calzone alla Nutella"]
    },
    {
        id: 15,
        name: "Flavio al Velavevodetto",
        category: "trattoria",
        categoryLabel: "Trattoria",
        rating: 4.7,
        lat: 41.8752,
        lng: 12.4794,
        address: "Via di Monte Testaccio, 97, Roma",
        quote: "Dentro al Monte dei Cocci, cucina romana che è un delitto!",
        specialties: ["Carbonara", "Amatriciana", "Coda alla Vaccinara"]
    },
    {
        id: 16,
        name: "Sbanco",
        category: "pizza",
        categoryLabel: "Pizza",
        rating: 4.6,
        lat: 41.9332,
        lng: 12.4678,
        address: "Via Siracusa, 13-15, Roma",
        quote: "Pizza contemporanea che rispetta la tradizione!",
        specialties: ["Pizza Gourmet", "Fritti"]
    },
    {
        id: 17,
        name: "Armando al Pantheon",
        category: "trattoria",
        categoryLabel: "Trattoria",
        rating: 4.7,
        lat: 41.8986,
        lng: 12.4762,
        address: "Salita dei Crescenzi, 31, Roma",
        quote: "Vicino al Pantheon ma prezzi e qualità da romani veri!",
        specialties: ["Carciofi", "Pasta e Ceci", "Abbacchio"]
    },
    {
        id: 18,
        name: "Mondo Arancina",
        category: "street-food",
        categoryLabel: "Street Food",
        rating: 4.4,
        lat: 41.9011,
        lng: 12.4727,
        address: "Via Marcantonio Colonna, 38, Roma",
        quote: "Arancine siciliane a Roma fatte come Dio comanda!",
        specialties: ["Arancina al Ragù", "Arancina al Pistacchio"]
    },
    {
        id: 19,
        name: "Trattoria Da Teo",
        category: "trattoria",
        categoryLabel: "Trattoria",
        rating: 4.6,
        lat: 41.8853,
        lng: 12.4684,
        address: "Piazza dei Ponziani, 7a, Roma",
        quote: "I carciofi alla giudia so' da standing ovation!",
        specialties: ["Carciofi alla Giudia", "Fiori di Zucca", "Carbonara"]
    },
    {
        id: 20,
        name: "La Gatta Mangiona",
        category: "pizza",
        categoryLabel: "Pizza",
        rating: 4.7,
        lat: 41.8652,
        lng: 12.4527,
        address: "Via Federico Ozanam, 30-32, Roma",
        quote: "Pizza gourmet a Monteverde che vale il viaggio!",
        specialties: ["Pizza con Burrata", "Supplì"]
    }
];
